type: object
required:
  - id
  - type
  - title
  - owner
  - owner_id
  - description
  - published
  - location
  - category
properties:
  id:
    readOnly: true
    type: integer
    format: int32
    description: Identificador único
    minimum: 1
    example: 1234
  type:
    type: string
    description: Tipo de anuncio
    enum:
      - sale
      - auction
    example: 'sale'
  title:
    type: string
    description: Descripción breve o nombre corto
    minLength: 1
    maxLength: 50
    example: 'Renault R11 1.4 GTL'
  owner:
    allOf:
      - readOnly: true
      - $ref: '#/components/schemas/User'
  owner_id:
    writeOnly: true
    type: integer
    format: int32
    description: Identificador único de propietario
    minimum: 1
    example: 345
  description:
    type: string
    description: Descripción detallada.
    example: 'Color gris/plata. Año 1986. 47000 km. El coche está en perfecto estado.'
  published:
    readOnly: true
    type: string
    format: date-time
    description: Fecha de publicacaión (UTC)
    pattern: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    example: 2017-07-21T17:32:28Z
  location:
    $ref: '#/components/schemas/Location'
  distance:
    nullable: true
    readOnly: true
    type: integer
    format: int32
    description: Distancia lineal (en km) al punto de referencia (si fue especificado en la petición).
    minimum: 1
  category:
    type: string
    description: Categoría a la que pertenece
    example: 'Automoción'
  media:
    readOnly: true
    type: array
    items:
      $ref: '#/components/schemas/Picture'
    description: Lista de imágenes. La primera imagen es la minuatura
  media_id:
    writeOnly: true
    type: array
    items:
      type: integer
      format: int32
      description: Identificador único
      minimum: 1
      example: 35749
    description: Lista de imágenes. La primera imagen es la minuatura
description: Representación de un Producto.