get:
  tags:
    - products
  summary: Obtener lista de Productos
  description: >-
    Carga una lista con todos los Productos registrados en la aplicación que
    cumplen las condiciones.
  parameters:
    - name: lat
      in: query
      required: true
      description: Latitud del punto de referencia
      example: -34.397
      schema:
        type: number
        minimum: -90
        maximum: 90
    - name: lng
      in: query
      required: true
      description: Longitud del punto de referencia
      example: 150.644
      schema:
        type: number
        minimum: -180
        maximum: 180
    - name: distance
      in: query
      required: true
      description: Distancia lineal máxima (en km) al punto de referencia
      example: 50
      schema:
        type: integer
        format: int32
        minimum: 1
    - name: types
      in: query
      description: Tipo(s) de Productos a mostrar
      example: '?types=sale&types=auction'
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
          enum:
            - sale
            - auction
    - name: category
      in: query
      required: false
      description: Categoría en la que buscar
      example: 'Automoción'
      schema:
        type: string
    - name: search
      in: query
      required: false
      description: Consulta por texto
      example: 'Teléfono Android'
      schema:
        type: string
    - name: priceFrom
      in: query
      required: false
      description: Precio mínimo a mostrar
      example: 1000
      schema:
        type: integer
        format: int32
        minimum: 0
    - name: priceTo
      in: query
      required: false
      description: Precio máximo a mostrar
      example: 3500
      schema:
        type: integer
        format: int32
        minimum: 0
    - name: publishedFrom
      in: query
      required: false
      description: Fecha de publicación mínima a mostrar
      example: '1970-01-01'
      schema:
        type: string
        format: date
    - name: publishedTo
      in: query
      required: false
      description: Fecha de publicación máxima a mostrar
      example: '1970-01-01'
      schema:
        type: string
        format: date
    - name: owner
      in: query
      required: false
      description: Propietario de los productos.
      example: 345
      schema:
        type: integer
        format: int32
    - name: status
      in: query
      required: false
      description: Estado de la venta.
      example: "en venta"
      schema:
        type: string
        enum:
          - "en venta"
          - "vendido"
    - name: $size
      in: query
      required: false
      description: Tamaño de la página.
      example: 10
      schema:
        type: integer
        minimum: 1
    - name: $page
      in: query
      required: false
      description: Número de página.
      example: 1
      schema:
        type: integer
        minimum: 1
    - name: $sort
      in: query
      required: false
      description: Atributo(s) por los que ordenar
      example: 'distance ASC, published DESC'
      schema:
        type: string
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              oneOf:
                - $ref: '#/components/schemas/Sale'
                - $ref: '#/components/schemas/Auction'
              discriminator:
                propertyName: type
                mapping:
                  sale: '#/components/schemas/Sale'
                  auction: '#/components/schemas/Auction'
post:
  tags:
    - products
  summary: Crear nuevo Producto
  description: Añade un Producto a la aplicación
  requestBody:
    content:
      application/json:
        schema:
          oneOf:
            - $ref: '#/components/schemas/Sale'
            - $ref: '#/components/schemas/Auction'
          discriminator:
            propertyName: type
            mapping:
              sale: '#/components/schemas/Sale'
              auction: '#/components/schemas/Auction'
    required: true
  responses:
    '201':
      description: Creado (nuevo producto creado)
    '401':
      description: No autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            default:
              $ref: '#/components/examples/401'
    '402':
      description: Prohibido (sin permisos para asociar al propietario)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            default:
              $ref: '#/components/examples/402'
